### ISSUE TITLE
Team Page 

### ISSUE THREAD

**Issue by Aniket762** [Aniket762/Webwiz-revamp#2]
Make the page responsive so that in the mobile screen it one card is displayed and in the laptop screen 3 cards in a row.  Just need to work on making it responsive. Attach a screenshot of the changes you did.

Expected view in laptop screen <img src= 'https://reactgo.com/static/791c7c76595c8515146e712bdf5fb8fe/07a9c/material-ui-grid-component.png'>

**Comment by Mallikarjunople** [comment]
I would like to work on this issue.

**Comment by Aniket762** [comment]
Hey @Mallikarjunople  go for it🚀
