### ISSUE TITLE
Setting up CI/CD workflow for React  

### ISSUE THREAD

**Issue by Aniket762** [Aniket762/Webwiz-revamp#4]
# Add auto checks when a PR is sent. [Refernce](https://dev.to/dyarleniber/setting-up-a-ci-cd-workflow-on-github-actions-for-a-react-app-with-github-pages-and-codecov-4hnp#:~:text=GitHub%20provides%20preconfigured%20workflow%20templates,to%20build%20your%20custom%20workflow.)
<img src='https://res.cloudinary.com/practicaldev/image/fetch/s--uXcJ1Eo1--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/i/37oyplfzlr7adilwf8r2.png'>

**Comment by aman0408** [comment]
Can I give it a try?
