### ISSUE TITLE
Team Section fix in home page

### ISSUE THREAD

**Issue by Aniket762** [Aniket762/Webwiz-revamp#9]
### Move the #team and button to the respective positions marked. Also check if the page is responsive if not please make it

![wr12fix](https://user-images.githubusercontent.com/67703407/115377496-4d3b8700-a1ed-11eb-8ed3-66e317339bd7.png)

## Attach a screenshot before sending a Pull Request🐱‍👤

**Comment by sumana2001** [comment]
I want to contribute. Please assign it to me

**Comment by Aniket762** [comment]
@sumana2001 go for it 🔥
